### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Andrey1994** [tmonseigne/RIGBy-cpp#2]
Hi!

I've not tried this library but it looks great.

I would like to try to integrate it into one of my projects(https://github.com/brainflow-dev/brainflow) but I need MIT compatible license... Did you consider MIT compatible licenses by any chance?

**Comment by tmonseigne** [comment]
Hi, Sorry I can't change. But for compatibility I don't know if it's a problem to use this in MIT Software. I follow the rule of the IT department.^^
Thibaut

**Comment by Andrey1994** [comment]
No problem, I expected it. Just wanted to confirm.

<<  I don't know if it's a problem to use this in MIT Software.
It's a problem, if GPL code is used in other project this project also must be distributed under GPL... It's very invasive license
